GearRemove = (vehicle player);
removeAllWeapons GearRemove;
removeAllItems GearRemove;
removebackpack GearRemove;


GearAdd = (vehicle player);
GearAdd addWeapon 'M4A1_HWS_GL_camo';
GearAdd addMagazine '30Rnd_556x45_Stanag';
GearAdd addMagazine '30Rnd_556x45_Stanag';
GearAdd addMagazine '30Rnd_556x45_Stanag';
GearAdd addMagazine '30Rnd_556x45_Stanag';
GearAdd addMagazine 'Skin_Sniper1_DZ';
GearAdd addMagazine 'ItemMorphine';
GearAdd addMagazine 'ItemBloodbag';
GearAdd addMagazine 'ItemPainkiller'; 
GearAdd addMagazine 'ItemEpinephrine';
GearAdd addMagazine 'ItemSodaPepsi';
GearAdd addWeapon 'M9SD';
GearAdd addMagazine '15Rnd_9x19_M9SD';
GearAdd addMagazine '15Rnd_9x19_M9SD';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine '1Rnd_HE_M203';
GearAdd addMagazine 'FlareGreen_M203';
GearAdd addWeapon 'ItemMap';
GearAdd addWeapon 'ItemWatch';
GearAdd addWeapon 'ItemHatchet';
GearAdd addWeapon 'ItemKnife';
GearAdd addWeapon 'Itemmatchbox';
GearAdd addWeapon 'Itemetool';
GearAdd addWeapon 'Itemtoolbox';
GearAdd addBackpack 'DZ_ALICE_Pack_EP1';
