private ["_classname","_item","_uniqueid"];
_classname = "USBasicWeapons_EP1";
_item = _classname createVehicleLocal (position player);

clearWeaponCargoGlobal _item;
clearMagazineCargoGlobal _item;
clearBackpackCargoGlobal _item;
_item addWeaponCargoGlobal ["Binocular", 2];
_item addWeaponCargoGlobal ["Binocular_Vector", 2];
_item addWeaponCargoGlobal ["ItemCompass", 2];
_item addWeaponCargoGlobal ["ItemCrowbar", 2];
_item addWeaponCargoGlobal ["ItemEtool", 2];
_item addWeaponCargoGlobal ["ItemFishingPole", 2];
_item addWeaponCargoGlobal ["ItemFlashlight", 2];
_item addWeaponCargoGlobal ["ItemFlashlightRed", 2];
_item addWeaponCargoGlobal ["ItemGPS", 2];
_item addWeaponCargoGlobal ["ItemHatchet", 2];
_item addWeaponCargoGlobal ["ItemKeyKit", 2];
_item addWeaponCargoGlobal ["ItemKnife", 2];
_item addWeaponCargoGlobal ["ItemMap", 2];
_item addWeaponCargoGlobal ["ItemMatchbox", 2];
_item addWeaponCargoGlobal ["ItemRadio", 2];
_item addWeaponCargoGlobal ["ItemSledge", 2];
_item addWeaponCargoGlobal ["ItemToolbox", 2];
_item addWeaponCargoGlobal ["ItemWatch", 2];
_item addWeaponCargoGlobal ["NVGoggles", 2];
_item addMagazineCargoGlobal ["plot_pole_kit", 2];
_item addMagazineCargoGlobal ["bulk_ItemTankTrap", 10];
_item addMagazineCargoGlobal ["cinder_door_kit", 50];
_item addMagazineCargoGlobal ["cinder_garage_kit", 50];
_item addMagazineCargoGlobal ["full_cinder_wall_kit", 50];
_item addMagazineCargoGlobal ["ItemComboLock", 10];
_item addMagazineCargoGlobal ["ItemLockbox", 2];
_item addMagazineCargoGlobal ["ItemVault", 2];
_item addMagazineCargoGlobal ["metal_floor_kit", 50];
_item addMagazineCargoGlobal ["metal_panel_kit", 10];
_item addMagazineCargoGlobal ["MortarBucket", 50];
_item addMagazineCargoGlobal ["CinderBlocks", 50];
_item addMagazineCargoGlobal ["ItemPole", 30];
_item addMagazineCargoGlobal ["ItemWire", 10];
_item addBackpackCargoGlobal ["DZ_LargeGunBag_EP1", 1];
_item setVariable ["permaLoot",true];
titleText [format["Crate spawned!"],"PLAIN DOWN"]; titleFadeOut 4;

_distance = 100;

waitUntil {(player distance _item) > _distance};
deleteVehicle _item;
titleText ["crate was deleted","PLAIN DOWN"]; titleFadeOut 4;
