private ["_classname","_item","_uniqueid"];
_classname = "USBasicWeapons_EP1";
_item = _classname createVehicleLocal (position player);
clearWeaponCargoGlobal _item;
clearMagazineCargoGlobal _item;
clearBackpackCargoGlobal _item;

_item addWeaponCargoGlobal ["Binocular", 2];
_item addWeaponCargoGlobal ["Binocular_Vector", 2];
_item addWeaponCargoGlobal ["ItemCompass", 2];
_item addWeaponCargoGlobal ["ItemCrowbar", 2];
_item addWeaponCargoGlobal ["ItemEtool", 2];
_item addWeaponCargoGlobal ["ItemFishingPole", 2];
_item addWeaponCargoGlobal ["ItemFlashlight", 2];
_item addWeaponCargoGlobal ["ItemFlashlightRed", 2];
_item addWeaponCargoGlobal ["ItemGPS", 2];
_item addWeaponCargoGlobal ["ItemHatchet", 2];
_item addWeaponCargoGlobal ["ItemKeyKit", 2];
_item addWeaponCargoGlobal ["ItemKnife", 2];
_item addWeaponCargoGlobal ["ItemMap", 2];
_item addWeaponCargoGlobal ["ItemMatchbox", 2];
_item addWeaponCargoGlobal ["ItemRadio", 2];
_item addWeaponCargoGlobal ["ItemSledge", 2];
_item addWeaponCargoGlobal ["ItemToolbox", 2];
_item addWeaponCargoGlobal ["ItemWatch", 2];
_item addWeaponCargoGlobal ["NVGoggles", 2];
_item addMagazineCargoGlobal ["bulk_ItemWire",  11];
_item addMagazineCargoGlobal ["deer_stand_kit", 11];
_item addMagazineCargoGlobal ["desert_large_net_kit", 11];
_item addMagazineCargoGlobal ["desert_net_kit", 11];
_item addMagazineCargoGlobal ["forest_large_net_kit", 11];
_item addMagazineCargoGlobal ["forest_net_kit", 11];
_item addMagazineCargoGlobal ["fuel_pump_kit", 11];
_item addMagazineCargoGlobal ["ItemHotwireKit", 11];
_item addMagazineCargoGlobal ["ItemJerrycan", 11];
_item addMagazineCargoGlobal ["ItemSandbag", 11];
_item addMagazineCargoGlobal ["ItemSandbagLarge", 11];
_item addMagazineCargoGlobal ["ItemCorrugated", 11];
_item addMagazineCargoGlobal ["ItemFireBarrel_Kit", 11];
_item addMagazineCargoGlobal ["ItemFuelBarrelEmpty", 11];
_item addMagazineCargoGlobal ["ItemGenerator", 11];
_item addMagazineCargoGlobal ["ItemTent", 11];
_item addMagazineCargoGlobal ["ItemTentDomed",  11];
_item addMagazineCargoGlobal ["ItemTentDomed2", 11];
_item addMagazineCargoGlobal ["ItemTentOld",  11];
_item addMagazineCargoGlobal ["bulk_ItemWire", 11];
_item addMagazineCargoGlobal ["light_pole_kit", 11];
_item addMagazineCargoGlobal ["m240_nest_kit", 11];
_item addMagazineCargoGlobal ["outhouse_kit", 11];
_item addMagazineCargoGlobal ["park_bench_kit", 11];
_item addMagazineCargoGlobal ["rusty_gate_kit", 11];
_item addMagazineCargoGlobal ["sandbag_nest_kit", 11];
_item addMagazineCargoGlobal ["stick_fence_kit", 11];
_item addMagazineCargoGlobal ["storage_shed_kit", 11];
_item addMagazineCargoGlobal ["sun_shade_kit", 11];
_item addMagazineCargoGlobal ["wooden_shed_kit", 11];
_item addMagazineCargoGlobal ["wood_shack_kit", 11];
_item addMagazineCargoGlobal ["metal_panel_kit", 11];
_item addBackpackCargoGlobal ["DZ_LargeGunBag_EP1", 1];
_item setVariable ["permaLoot",true];
titleText [format["Crate spawned!"],"PLAIN DOWN"]; titleFadeOut 4;

_distance = 100;

waitUntil {(player distance _item) > _distance};
deleteVehicle _item;
titleText ["crate was deleted","PLAIN DOWN"]; titleFadeOut 4;
