private ["_classname","_item","_uniqueid"];
_classname = "USBasicWeapons_EP1";
_item = _classname createVehicleLocal (position player);
clearWeaponCargoGlobal _item;
clearMagazineCargoGlobal _item;
clearBackpackCargoGlobal _item;
_item addWeaponCargoGlobal ["Binocular", 2];
_item addWeaponCargoGlobal ["Binocular_Vector", 2];
_item addWeaponCargoGlobal ["ItemCompass", 2];
_item addWeaponCargoGlobal ["ItemCrowbar", 2];
_item addWeaponCargoGlobal ["ItemEtool", 2];
_item addWeaponCargoGlobal ["ItemFishingPole", 2];
_item addWeaponCargoGlobal ["ItemFlashlight", 2];
_item addWeaponCargoGlobal ["ItemFlashlightRed", 2];
_item addWeaponCargoGlobal ["ItemGPS", 2];
_item addWeaponCargoGlobal ["ItemHatchet", 2];
_item addWeaponCargoGlobal ["ItemKeyKit", 2];
_item addWeaponCargoGlobal ["ItemKnife", 2];
_item addWeaponCargoGlobal ["ItemMap", 2];
_item addWeaponCargoGlobal ["ItemMatchbox", 2];
_item addWeaponCargoGlobal ["ItemRadio", 2];
_item addWeaponCargoGlobal ["ItemSledge", 2];
_item addWeaponCargoGlobal ["ItemToolbox", 2];
_item addWeaponCargoGlobal ["ItemWatch", 2];
_item addWeaponCargoGlobal ["Laserdesignator", 2];
_item addWeaponCargoGlobal ["NVGoggles", 2];
_item addMagazineCargoGlobal ["plot_pole_kit", 2];
_item addMagazineCargoGlobal ["ItemComboLock", 10];
_item addMagazineCargoGlobal ["ItemLockbox", 2];
_item addMagazineCargoGlobal ["ItemVault", 2];
_item addMagazineCargoGlobal ["ItemWoodFloor", 50];
_item addMagazineCargoGlobal ["ItemWoodFloorHalf", 20];
_item addMagazineCargoGlobal ["ItemWoodFloorQuarter", 10];
_item addMagazineCargoGlobal ["ItemWoodLadder", 10];
_item addMagazineCargoGlobal ["ItemWoodStairsSupport", 10];
_item addMagazineCargoGlobal ["ItemWoodWall", 50];
_item addMagazineCargoGlobal ["ItemWoodWallDoor", 30];
_item addMagazineCargoGlobal ["ItemWoodWallDoorLg", 30];
_item addMagazineCargoGlobal ["ItemWoodWallGarageDoor", 30];
_item addMagazineCargoGlobal ["ItemWoodWallLg", 30];
_item addMagazineCargoGlobal ["ItemWoodWallThird", 15];
_item addMagazineCargoGlobal ["ItemWoodWallWindow", 10];
_item addMagazineCargoGlobal ["ItemWoodWallWindowLg", 10];
_item addMagazineCargoGlobal ["ItemWoodWallWithDoor", 30];
_item addMagazineCargoGlobal ["ItemWoodWallwithDoorLg", 24];
_item addMagazineCargoGlobal ["wood_ramp_kit", 5];
_item addMagazineCargoGlobal ["workbench_kit", 1];
_item addBackpackCargoGlobal ["DZ_LargeGunBag_EP1", 1];
_item setVariable ["permaLoot",true];
titleText [format["Crate spawned!"],"PLAIN DOWN"]; titleFadeOut 4;


_distance = 100;

waitUntil {(player distance _item) > _distance};
deleteVehicle _item;
titleText ["crate was deleted","PLAIN DOWN"]; titleFadeOut 4;